required = ["github.com/gobuffalo/packr"]

[[constraint]]
  name = "github.com/emicklei/proto"
  version = "^1.2.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "^1.4.7"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/vendasta/gosdks"
  version = "^13.25.0"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "v2.7.1"
