[[constraint]]
  name = "github.com/emicklei/proto"
  version = "^1.2.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "^1.4.7"

[[constraint]]
  branch = "master"
  name = "github.com/oliveagle/jsonpath"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/vendasta/gosdks"
  version = "^13.25.0"

[[constraint]]
  name = "github.com/vendasta/mscli"
  version = "^5.5.1"
